name: Makefile CI

on:
  workflow_dispatch:
  #push:
  #  branches: [ "*" ]
  #pull_request:
  #  branches: [ "*" ]

jobs:
  build_wav:
    name: build wav file
    runs-on: ubuntu-22.04
    env:
      TOOLCHAIN_PATH: /usr/local/arm/arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi

    steps:
    
    - uses: actions/checkout@v4
    
    - name: setup arm toolchain
      run: |
        mkdir -p /usr/local/arm
        pushd /usr/local/arm
        echo "Downloading to slightly different name to match name of extracted folder: arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi"
        wget -O "/usr/local/arm/arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi" "https://developer.arm.com/-/media/Files/downloads/gnu/13.2.rel1/binrel/arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi.tar.xz?rev=e434b9ea4afc4ed7998329566b764309&hash=CA590209F5774EE1C96E6450E14A3E26"
        tar -xf arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi
        tree arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi
        popd
        
    - name: make wav
      run: |
        pwd
        make -f stages/makefile wav

